#pragma once
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <iostream>
#include <fstream>
#include <vector>
#include <queue>
#include <mutex>
#include <random>
#include <cmath>
#include <memory>